Timeline_edit_button_icon:
  default: "pencil-alt"
  description:
    en: Choose an icon for the button. You can use any FontAwesome 4.7 icon name like "music" or "star" without quote marks. 
Timeline_edit_button_text:
  default: "Edit Topic"
  description:
    en: Edit
Timeline_edit_button_title:
  default: ""
  description:
    en: "Enter the title you want the button to use. If this is left empy, the title will be the same as the button text"
